version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: palaspapas_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: palaspapas
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - palaspapas_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: palaspapas_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - palaspapas_network
    depends_on:
      mysql:
        condition: service_healthy

networks:
  palaspapas_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local